default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: thalles
  password: user1234

development:
  <<: *default
  database: storage/development.sqlite3

